### ISSUE TITLE
[BREAKING] new hosting method

### ISSUE THREAD

**Issue by lorenzo132** [modmail-dev/Modmail#3182]
### Bot Version

all

### How are you hosting Modmail?

Other

### Error Logs

-

### Screenshots

-

### Additional Information

There is no sleeping function on Render like heroku offers for the logviewer. The change of hosting requires a merge of both logviewer and bot into 1 repo.

**Comment by StephenDaDev** [comment]
Oh boy here we go again

**Comment by Taaku18** [comment]
Duplicate of #2849.
