### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by Shinyzenith** [modmail-dev/Modmail#3198]
### Is your feature request related to a problem? Please elaborate.

Opt-in breaking changes according to semver would be nice instead of just pushing breaking changes to production and taking down a lot of bots...

### Describe the solution you'd like

Look above

### Does your solution involve any of the following?

- [ ] Logviewer
- [x] New config option

### Describe alternatives you've considered

N/A

### Who will this benefit?

Everyone

**Comment by sebkuip** [comment]
V4 has been discussed and has been a hot topic in the discord server. It's also been the development version and was planned to come around this time.

You can also disable auto updates if you wish to not automatically receive updates that might break changes.

**Comment by Shinyzenith** [comment]
> V4 has been discussed and has been a hot topic in the discord server. It's also been the development version and was planned to come around this time.
> 
> You can also disable auto updates if you wish to not automatically receive updates that might break changes.

I actually do want auto-updates but only for things like security patches etc.. Breaking semver changes as opt-in reactions in the log channel would be really nice ( or maybe buttons ? )
