### ISSUE TITLE
[BUG]: guild icon invalid

### ISSUE THREAD

**Issue by CrowAndBoots4419** [modmail-dev/modmail#3205]
### Bot Version

4.0.1

### How are you hosting Modmail?

Other

### Error Logs

https://hastebin.cc/isepucoled

### Additional Information

The bot will not close threads if there is not an icon set for the server. 
It is failing to return the default icon.

**Comment by Jerrie-Aries** [comment]
If this is going to get fixed, there are approximately 16 places that need to be edited in:
- `bot.py`
- `cogs/modmail.py`
- `cogs/utility.py`
- `core/thread.py`

**Comment by StephenDaDev** [comment]
This was resolved by #3235. Thank you to our community for helping to fix this issue.
