### ISSUE TITLE
Plain message customization

### ISSUE THREAD

**Issue by Esperita** [modmail-dev/Modmail#3230]
### Is your feature request related to a problem? Please elaborate.

I would like to make the discussions looking like a normal conversation in the eyes of the users. But I'm not able to remove the (): before every plain messages.

### Describe the solution you'd like

Removing (): from the hard code and add them in the variation text that we can configure.

### Does your solution involve any of the following?

- [ ] Logviewer
- [X] New config option

### Describe alternatives you've considered

An option to disable username and tag in plain text.

### Who will this benefit?

Every users.

### Additional Information

![image](https://user-images.githubusercontent.com/118846635/203393094-b41080ae-e270-4cfb-a475-23bad5d28bed.png)
![image](https://user-images.githubusercontent.com/118846635/203393208-f0be45c0-0db5-4683-8666-972629caef60.png)
![image](https://user-images.githubusercontent.com/118846635/203393312-965bda4e-cae2-4bb1-bd09-e32a815e8be9.png)

**Comment by StephenDaDev** [comment]
Did #3234 Fully accomplish what you wanted here?

**Comment by StephenDaDev** [comment]
PR Merged
