### ISSUE TITLE
Allow "user replying" messeges to be sent to the thread

### ISSUE THREAD

**Issue by EGGamer** [modmail-dev/Modmail#3238]
### Is your feature request related to a problem? Please elaborate.

In a modmail thread, if the user sends a message but replies to a bot message, it won't be sent to the thread, confusing the users.

![How the user sees the threads](https://i.imgur.com/KqLzH1I.png)
![How the staff sees the thread](https://i.imgur.com/Dhfs09B.png)

### Describe the solution you'd like

I think it would be great if the bot sent to the thread all the messages the user sends, even if it's a normal message or a replying message. 

### Does your solution involve any of the following?

- [ ] Logviewer
- [ ] New config option

### Describe alternatives you've considered

If the solution above can't be done, it would be great to indicate with a ❌ emoji that the message wasn't sent.

### Who will this benefit?

Modmail users mostly, as it can confuse them.

**Comment by StephenDaDev** [comment]
The PR has been merged into our development branch and will be applied on the next production update
