### ISSUE TITLE
[BUG]: Support new usernames

### ISSUE THREAD

**Issue by rabeehrz** [modmail-dev/Modmail#3287]
### Bot Version

4.0.1

### How are you hosting Modmail?

Other

### Error Logs

https://i.imgur.com/qhrdIjC.png

### Screenshots

With Discord introducing new usernames, the embed the bot generates for reply contains `#0` as the default discriminator.

I think only the username should be displayed.

![](https://i.imgur.com/qhrdIjC.png)

In the above image, It should be `aer` instead of `aer#0`

**Comment by byayex** [comment]
Would recommend waiting for changes on this until the new usernames are 100% rolled out.
