### ISSUE TITLE
Fix code scanning alert - Incomplete URL substring sanitization

### ISSUE THREAD

**Issue by Taaku18** [modmail-dev/Modmail#3291]
Tracking issues for:
- [ ] https://github.com/modmail-dev/Modmail/security/code-scanning/1
- [ ] https://github.com/modmail-dev/Modmail/security/code-scanning/2

I don't see how these are vulnerabilities. But since CodeQL says so, I'll replace it with a better way.

**Comment by RealCyGuy** [comment]
I don't think it's a vulnerability, but it could cause unexpected behaviour if an image url was https://gyazo.com.example.com/image.png for example.
