### ISSUE TITLE
Mention variable - freply

### ISSUE THREAD

**Issue by lorenzo132** [modmail-dev/Modmail#3294]
### Is your feature request related to a problem? Please elaborate.

Currently there is no way to @mention a user in a thread with freply or reply, without having to manually copy someones userid.

### Describe the solution you'd like

a {user.mention} variable in the freply command

### Does your solution involve any of the following?

- [ ] Logviewer
- [ ] New config option

### Describe alternatives you've considered

-

### Who will this benefit?

Anyone using modmail.

**Comment by martinbndr** [comment]
This is already a thing with {recipient.mention} for the thread creator and {author.mention} for the user that used the command.

**Comment by lorenzo132** [comment]
Let me change this feature request a little bit, adding a config for anon freply would be amazing
