### ISSUE TITLE
[BUG]: Modmail does not support StickerFormatType 4

### ISSUE THREAD

**Issue by Cyxo** [modmail-dev/Modmail#3316]
### Bot Version

4.0.2

### How are you hosting Modmail?

Other

### Error Logs

https://pastebin.pl/view/020b388f

### Additional Information

Discord.py 2.0.1 doesn't support StickerFormatType 4, which made our modmail crash when we added a sticker of that type (I can't tell what exactly type 4 is though, it was just a regular GIF).

It was fixed in the following commit of discord.py: https://github.com/Rapptz/discord.py/commit/eb06129378e130ab5681489ec061690b3f68273d
I don't think support for type 4 was added before discord.py version 2.3.2 (currently the latest).

**Comment by sebkuip** [comment]
Already fixed in dev. Currently in testing before update is released to stable release.
