### ISSUE TITLE
Make bot type in text channel when user is typing

### ISSUE THREAD

**Issue by wdhdev** [modmail-dev/Modmail#3327]
### Is your feature request related to a problem? Please elaborate.

Make the bot start typing in the ticket channel when the user starts typing so staff can know when the user is typing in DMs with the bot.

### Describe the solution you'd like

When the bot detects the user typing in DMs and has an open ticket, make the bot start typing in the ticket channel which staff can see.

### Does your solution involve any of the following?

- [ ] Logviewer
- [ ] New config option

### Describe alternatives you've considered

N/A

### Who will this benefit?

It's just a QOL feature so staff know when the user is typing.

**Comment by Zinoviya99** [comment]
This is already a feature... please see
`?config help user_typing`

**Comment by wdhdev** [comment]
Sorry I didn't see that! Sorry for wasting your time.
