### ISSUE TITLE
[BUG]: Critical Error saying "TOKEN must be set..."

### ISSUE THREAD

**Issue by KoreyMiracle** [modmail-dev/Modmail#3331]
### Bot Version

v4.1.0

### How are you hosting Modmail?

Self-hosting

### Error Logs

Not using heroku

### Screenshots

![CRITICAL](https://github.com/modmail-dev/Modmail/assets/150237532/0c22232f-6f40-4897-9fe9-6eea62394102)

**Comment by sebkuip** [comment]
Not a bug. Please follow the install guide how to use our bot. https://beta.docs.modmail.dev/
