### ISSUE TITLE
[BUG]: Moduleimport error 

### ISSUE THREAD

**Issue by achyut2006** [modmail-dev/Modmail#3350]
### Bot Version

v4.1

### How are you hosting Modmail?

Other

### Error Logs

Logs above.

### Screenshots

![IMG_6056](https://github.com/user-attachments/assets/777232ed-8a50-48c8-b1bc-b77876d07928)

### Additional Information

I am unable to start the code, due to an import error.

**Comment by Zinoviya99** [comment]
I assume this is a pterodactyl panel, of the bot hosting kind. If I am correct and you have already installed everything it's a bug on your hosting side not on us. You'll need to take it up with them.
